winget install -e --id Twilio.Authy --force	--accept-source-agreements 
winget install -e --id Canonical.Ubuntu.2204 --force --accept-source-agreements 
winget install -e --id Microsoft.VisualStudioCode --force --accept-source-agreements
winget install -e --id Notepad++.Notepad++ --force --accept-source-agreements
winget install -e --id Microsoft.PowerToys --force --accept-source-agreements
winget install -e --id CPUID.HWMonitor --force --accept-source-agreements
winget install -e --id CPUID.CPU-Z --force --accept-source-agreements
winget install -e --id WireGuard.WireGuard --force --accept-source-agreements
winget install -e --id ByteDance.CapCut --force --accept-source-agreements
winget install -e --id Postman.Postman.DesktopAgent --force --accept-source-agreements
